name: GQ Sound
favicon: null
layout_spectrum: 0.17013812786899507
typography_spectrum: 0.9445021240971982
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6862495227251202
  lightness: 0.08729066420346498
  saturation: 0.06379362870939076
  rhythmicContrast: 0.5080492857377976
purpose: []
