name: GQ Sound
favicon: null
layout_spectrum: 0.17013812786899507
typography_spectrum: 0.9445021240971982
title: 'GQ Sound '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74057422-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f69220'
    - '#000000'
    - '#1e2da0'
    - '#375fa0'
    - '#0000ff'
  brandStrength: 0.125
  lightness: 0.08729066420346498
  saturation: 0.06379362870939076
  rhythmicContrast: 0.5080492857377976
purpose: []
