name: GQ Sound
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10366
title: 'GQ Sound '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74057422-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e3ebd7'
    - '#3b3038'
    - '#8a776a'
    - '#a42c37'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.5080492857377976
purpose: []
